spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
      username: root
      password: lyc123

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.example.mybatis.pojo
  mapperLocations: classpath:mapper/*.xml